[package]
name = "porpoise-ssh"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "SSH connections, sessions, and port forwarding"

[dependencies]
porpoise-core = { path = "../porpoise-core" }
tokio.workspace = true
ssh2 = "0.9"
zeroize.workspace = true

[dev-dependencies]
